[package]
name = 'pallet-kitties'
authors = ['David Rhodus']
edition = '2018'
version = '0.1.0'
readme = 'README.md'



[dependencies]
codec = { default-features = false, features = ['derive'], package = 'parity-scale-codec', version = '2.0.0' }
frame-system = { default-features = false, version = '3.0.0' }
frame-support = { default-features = false, version = '3.0.0' }

sp-std = { default-features = false, version = '3.0.0' }


[features]
default = ['std']
std = [
	'codec/std',
	'frame-support/std',
	'frame-system/std',
	'sp-std/std',
]

